### ISSUE TITLE
Balanced Annihilation rapid repo needs to be changed

### ISSUE THREAD

**Issue by ForbodingAngel** [spring/RapidTools#47]
To https://github.com/Balanced-Annihilation/Balanced-Annihilation

Floris and I have moved it to GitHub, as both of us are working on some very large things in BA and svn sucks at branching. After enough griping/whining/nudging from me about svn, Floris agreed to move it over to an organization on GitHub and that is where all new changesets are happening.

**Comment by abma** [comment]
is BAR planned to be moved as well?

**Comment by abma** [comment]
edit: BACD should be migrated as well

(these are the last svn repositories in spring community)

**Comment by abma** [comment]
https://github.com/Balanced-Annihilation/Balanced-Annihilation/issues/1

**Comment by abma** [comment]
i'm waiting for a statement from either beherith or bluestone  (here or in public somewhere else) before switching. i hope thats understandable?!

**Comment by ForbodingAngel** [comment]
It really isn't.

**Comment by ForbodingAngel** [comment]
You do understand that Behe is not the maintainer nor does he have anyhting to do with BA anymore, correct? Additionally, Floris is the maintainer now and I have been doing a lot of it myself as well. Kind of on accident, but BA was very far behind in it's lua and various other things. I have added shitloads of functionality to be and I even set up the framework to entirely overhaul their effects (as in no more engine bullshit, CEGs and LUPS now).

Bluestone isn't involved either, for that matter. Decay was doing "Balance" (in other words, likes to play with numbers in a text editor), but he isn't involved anymore either. So holding this up for people who are no longer involved is silly to say the least.

BAR is it's own thing, neither I nor Floris are actively involved with BAR and at this point it's halfway dead in the water, but that's a sidenote.

**Comment by abma** [comment]
then at least a note from floris, please.

**Comment by abma** [comment]
https://springrts.com/phpbb/viewtopic.php?f=44&t=35660

**Comment by silentwings** [comment]
Afaics this request should come from Floris and Decay (and they may well want to make it). 

To the best of my knowledge FA is not in a position to speak for BA development, or listed anywhere as such; were this to change it would also be Floris and Decay that decided so - and committing to the repo does not automatically confer rights to speak for the project.

Afaics any repo move would need to consult Behe since he technically owns a CC-BY-ND license for all original content in the BA repo that is not otherwise marked with a license or is automatically GPL'ed code (there is not much; there is some). Moreover, it would be simple politeness to do so first, since he has provided BAs infra for many years, despite being mostly distanced in BA development.

I think that BAR is unlikely to move to git(hub), due to large numbers of prohibitively large data files, and the fact that neither myself or Behe (who remain as BARs developers) have ever wished to move it.

**Comment by abma** [comment]
IMHO we are at the point where BA/BAR must be released with a license which allows the project to continue without the original authors or we will have a similar state like SWIW very soon.

**Comment by ForbodingAngel** [comment]
Floris and I have been talking all along in BA's discord, conversations to which all of you are privy. I made the issue request on the behalf because Abma told me to, but Abma don't play dumb, it's not like you don't know. You were on IRC talking to Floris as I was helping him set up his git environment for BA.

What original content? It's all ripped from TA and with some CC0 stuff incorporated here and there. Unless you are counting "critters".

I PM'd behe about it almost a month ago and received no response, so the "politeness" was there. I never stated that I was speaking for the project not did I ever imply as such. I merely pointed out that neither you, behe, nor decay are even remotely actively involved in BA ongoing development and haven't been for quite some time.

**Comment by silentwings** [comment]
> BA's discord, conversations to which all of you are privy.
I am not, nor do I really know what it is.

> IMHO we are at the point where BA/BAR must be released with a license which allows the project to continue without the original authors 
In BAs case I agree but it is not me that is needed. In BARs case, I don't think so, yet.

**Comment by knorker** [comment]
> I have added shitloads of functionality to ba and I even set up the framework to entirely overhaul their effects (as in no more engine effects, CEGs and LUPS now)

After looking at commit timeline it is just inserting stuff other peoplers had made for your mod. The CEGs files have the same problems as last time. The blubbering about "engine-effects" and "performance" is bizarre when you still fail basics like how often per seconde something runs etc.
Adding OTA music after always whining how "BA is illegal crap" is a strange move. (Also file size.)
Instead of listing everything: Your understanding of spring modding is so bad anyone serious would tripple-check all files you touched to see what you messed up this time.

Do you not have your own mod to worry about?
Is this an attempt to cramp unfinished evolutionRTS stuff into a popular game, so it has higher chance of someone fixing it for you? Like the "advanced math problem" of capturePoint gadget to distribute n points in a spirale/circle pattern? 
Just wait until someone cares to reply to your chat whining, or make a bounty-post or find someone new and not yet pissed off by you to do it.
Instead of messing up a game you never played and always talk shit about.

**Comment by abma** [comment]
(deleted knorkes comment as he is banned on springrts forum.)

**Comment by knorker** [comment]
so?

**Comment by Ruwetuin** [comment]
I 've send Beherith, Bluestone and Decay a pm via the forum regardign the github move... 
Mainly to reach Beherith. But that was 11 Oct 2016, 20:31, and no response was given.

the pm:
> copy from #badev:
> 
> [21:25:55] <Floris> this exists now since today: https://github.com/balanced-annihilation
> [21:26:39] <@[Fx]Bluestone> did you speak to behe?
> [21:26:43] <Floris> no
> [21:27:02] <@[Fx]Bluestone> you probably should
> [21:27:09] <@[Fx]Bluestone> i doubt he'll mind but you technically just broke a license
> [21:27:24] <Floris> eh wut
> [21:27:56] <@[Fx]Bluestone> anything that isn't linking to engine or explicitly licensed otherwise in the BA repo is CC-BY-ND
> 
> I'm still figuring out how things work and should be done...
> 
> What are your thoughts on the licensing and the migration it github?

**Comment by Ruwetuin** [comment]
Nobody has been opposed it yet so yeah why not link rapid to it.

Decay hasnt been around much last half year and we need someone around who is active... but this isnt much related to the repo issue. This does however needs to be adressed sooner or later.

**Comment by abma** [comment]
ok, done.

thanks for the feedback. BACD / BAR needs more discussion + feedback from behe.

can you please poke me before you make the next stable release so that the new ba:stable tag will work? (else there will be two ba:stable tags which will result in weird stuff)

**Comment by abma** [comment]
wrt BACD i hope/think https://github.com/Balanced-Annihilation/Balanced-Annihilation/issues/3 is fine.

wrt BAR it should be discussed public in the ba forum?!
