### ISSUE TITLE
Add tcampaign to rapid

### ISSUE THREAD

**Issue by azaremoth** [spring/RapidTools#68]
Hi there,

please add [https://github.com/azaremoth/tcampaign](https://github.com/azaremoth/tcampaign)

It is a mutator for The Cursed that will contain the additional content required for a single player campaign current included in the Chobby for Cursed. This allows for content updates, while not screwing up the multiplayer content (main archive, autohosts)

With the usual tags:
tcampaign:test
tcampaign:stable

Thank you,
aZaremoth

**Comment by abma** [comment]
done!

**Comment by abma** [comment]
very likely you will hit https://github.com/springlobby/springlobby/commit/8f2d15af2afc22465ebe0237a8de779fe34b55f9 which prevents springlobby / pr-downloader from updating repos.gz with the new repository. this is fixed in the current version, so can you please check if current springlobby (0.268) works for you and give a small feedback about this?

https://springlobby.springrts.com/

soon springlobby.info will redirect to the new site, see https://springrts.com/phpbb/viewtopic.php?f=92&t=40429

thanks!
